<a href="https://colab.research.google.com/github/jullyoemmanuel/Servo/blob/main/2_VariavelEstado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Roteiro 2: Variáveis de Estado**

# Instalação dos pacotes

In [ ]:
!pip install control

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 398 kB 7.8 MB/s 
  Created wheel for control: filename=control-0.9.2-py2.py3-none-any.whl size=403205 sha256=3bc38963eb9e80e97b649cfc1b1bc5462049d91c719d8af8fe9f4aff0bf5a9b4
  Stored in directory: /root/.cache/pip/wheels/a6/3d/b3/8c508e66f4d44cf71b9ec49b94d4a074c8f2ee52475cd8920e
Successfully built control


# Importação das bibliotecas

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import control as co
import sympy as sp
import scipy 
import math

# Definição dos parâmetros das figuras

In [ ]:
# print no formato float com 3 dígitos
np.set_printoptions(formatter={'float': '{: 0.3f}' .format})
np.set_printoptions(precision=3)

In [ ]:
# caso seja necessário
plt.rcParams['figure.figsize']=[23, 10]
plt.rcParams['font.size']=24

# Exemplos do livro: Capítulo 3 

**Rode os códigos desta seção e acompanhe os exemplos em MATLAB apresentados no Anexo B.2 do livro "Engenharia de Sistemas de Controle" do Norman S. Nise, 6ª edição (pg 1122 a 1125)**

### ch3p1: declaração de matriz

In [ ]:
A = np.array([[0, 1, 0],[0, 0, 1],[-9, -8, -7]])
print(A)

[[ 0  1  0]
 [ 0  0  1]
 [-9 -8 -7]]


### ch3p2: declaração de vetor-linha e vetor-coluna

In [ ]:
C = np.array([[2, 3, 4]]) #vetor-linha
B = np.array([[7],[8],[9]]) #vetor-coluna
print(C)
print(B)

[[2 3 4]]
[[7]
 [8]
 [9]]


In [ ]:
# outra forma de declarar o vetor-coluna
B = np.array([[7, 8, 9]])
B = np.transpose(B)

print(C)
print(B)

[[2 3 4]]
[[7]
 [8]
 [9]]


### ch3p3: representação no espaço de estados

In [ ]:
D = np.array([[0]])
sys = co.StateSpace(A, B, C, D)
print(sys)

A = [[ 0.  1.  0.]
     [ 0.  0.  1.]
     [-9. -8. -7.]]

B = [[7.]
     [8.]
     [9.]]

C = [[2. 3. 4.]]

D = [[0.]]



In [ ]:
# Para acessar cada matriz:
A = sys.A
B = sys.B
C = sys.C
D = sys.D

display(A)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [-9., -8., -7.]])

In [ ]:
# método 2:
sys2 = co.ss(A,B,C,D)
print(sys2)

<LinearIOSystem>: sys[3]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ 0.  1.  0.]
     [ 0.  0.  1.]
     [-9. -8. -7.]]

B = [[7.]
     [8.]
     [9.]]

C = [[2. 3. 4.]]

D = [[0.]]



In [ ]:
# método 3:
Aa = "0 1 0; 0 0 1; -9 -8 -7"
Bb = "7; 8; 9"
Cc = "2, 3, 4"
Dd = "0"
sys3 = co.ss(Aa, Bb, Cc, Dd)
print(sys3)

<LinearIOSystem>: sys[4]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ 0.  1.  0.]
     [ 0.  0.  1.]
     [-9. -8. -7.]]

B = [[7.]
     [8.]
     [9.]]

C = [[2. 3. 4.]]

D = [[0.]]



### ch3p4: conversão de função de transferência para espaço de estados

In [ ]:
# declaração da FT
num = [24]
den = [1, 9, 26, 24]
FT = co.tf(num,den)

In [ ]:
# utilizando a biblioteca control (co)
SS = co.tf2ss(FT) # diretamente da FT
print(SS)

#SS = co.tf2ss(num,den) # a partir dos coeficientes do numerador e denominador
#print(SS)

A = [[ -9. -26. -24.]
     [  1.   0.   0.]
     [  0.   1.   0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[ 0.  0. 24.]]

D = [[0.]]



In [ ]:
# método 2: 
sys2 = co.ss(FT)
print(sys2)

<LinearIOSystem>: sys[7]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']
States (3): ['x[0]', 'x[1]', 'x[2]']

A = [[ -9. -26. -24.]
     [  1.   0.   0.]
     [  0.   1.   0.]]

B = [[1.]
     [0.]
     [0.]]

C = [[ 0.  0. 24.]]

D = [[0.]]



In [ ]:
#utilizando a biblioteca scipy
A, B, C, D = scipy.signal.tf2ss(num,den) # coeficientes do numerador e denominador
print('A = ', A)
print('B = ', B)
print('C = ', C)
print('D = ', D)

A =  [[ -9. -26. -24.]
 [  1.   0.   0.]
 [  0.   1.   0.]]
B =  [[1.]
 [0.]
 [0.]]
C =  [[ 0.  0. 24.]]
D =  [[0.]]


In [ ]:
# ch3p4: transformação na forma de variáveis de fase 
P = np.array([[0, 0, 1],[0, 1, 0],[1, 0, 0]])

Pinv =  np.linalg.inv(P)
Af = Pinv @ A @ P
Bf = Pinv @ B
Cf = C @ P
Df = D

print('A = ', Af)
print('B = ', Bf)
print('C = ', Cf)
print('D = ', Df)

A =  [[  0.   1.   0.]
 [  0.   0.   1.]
 [-24. -26.  -9.]]
B =  [[0.]
 [0.]
 [1.]]
C =  [[24.  0.  0.]]
D =  [[0.]]


### ch3p5: conversão de equações no espaço de estados para função de transferência

In [ ]:
# a partir das 4 matrizes
A = np.array([[0, 1, 0],[0, 0, 1],[-9, -8, -7]])
B = np.array([[7],[8],[9]])
C = np.array([[2, 3, 4]])
D = np.array([[0]])

sys2 = co.ss2tf(A, B, C, D)
print(sys2)


74 s^2 - 199 s - 235
---------------------
s^3 + 7 s^2 + 8 s + 9



In [ ]:
# a partir do sistema de espaço de estados
sys1 = co.ss(A, B, C, D)
sys2 = co.ss2tf(sys1)
print(sys2)


74 s^2 - 199 s - 235
---------------------
s^3 + 7 s^2 + 8 s + 9



# Resolução

## Questão 2
**Convertam as equações de estado e de saída mostradas abaixo em uma função de transferência**

$x = \begin{bmatrix} -4 & -1,5 \\ 4 & 0\end{bmatrix}x+ \begin{bmatrix} 2\\ 0 \end{bmatrix} u(t)$

$y = \begin{bmatrix} 1,5 & 0,625 \end{bmatrix}x$

In [ ]:
A = np.array([[-4, -1.5],[4, 0]])
B = np.array([[2],[0]])
C = np.array([[1.5, 0.625]])
D = np.array([[0]])

sys2 = co.ss2tf(A, B, C, D)
print(sys2)


   3 s + 5
-------------
s^2 + 4 s + 6



## Questão 3
**Obtenham as equações de estado e a equação de saída para a representação em variáveis de fase da função de transferência**

$$G(s) = \frac{2s+1}{(s+1)(s+3)(s^3+4s+5)}$$

In [ ]:
num1 = [2,1]
den1 = np.convolve([1,4,3],[1,0,4,5])
TF1 = co.tf(num1,den1)
print(TF1)


                2 s + 1
----------------------------------------
s^5 + 4 s^4 + 7 s^3 + 21 s^2 + 32 s + 15



In [ ]:
SS = co.tf2ss(num1,den1)
print(SS)

A = [[ -4.  -7. -21. -32. -15.]
     [  1.   0.   0.   0.   0.]
     [  0.   1.   0.   0.   0.]
     [  0.   0.   1.   0.   0.]
     [  0.   0.   0.   1.   0.]]

B = [[1.]
     [0.]
     [0.]
     [0.]
     [0.]]

C = [[0. 0. 0. 2. 1.]]

D = [[0.]]

